# Generated by Django 5.2.3 on 2025-06-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usersession_chatsessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsessions',
            name='chat_history',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='pdf_image_urls',
            field=models.TextField(blank=True, null=True),
        ),
    ]
