# Generated by Django 5.2.3 on 2025-06-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_chatsessions_chat_history_usersession_pdf_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
