# Generated by Django 5.2.3 on 2025-06-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_usersession_ocr_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='session_activity',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
