# Generated by Django 5.2.3 on 2025-06-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_usersession_session_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='session_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
