# Generated by Django 5.2.3 on 2025-06-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_usersession_session_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='session_name',
            field=models.CharField(max_length=225),
        ),
    ]
